apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: petclinic
  namespace: flux-system
spec:
  interval: 1m
  releaseName: petclinic
  targetNamespace: petclinic
  install:
    createNamespace: true
  chart:
    spec:
      chart: ../../../../app    # exact relative path from helmrelease.yaml to chart folder
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  values:
    replicaCount: 2
