namesapce: myapp-prod

replicaCount: 2

image:
  tag: "44"

hpa:
  minReplicas: 2
  maxReplicas: 10
  cpuUtilization: 60

resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

ingress:
  host: petclinic.mycompany.com
