apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: petclinic-dev
  namespace: myapp
spec:
  interval: 1m0s
  ref: 
    branch: main  
  url: https://github.com/rizjosel/petclinic-config.git
