apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: petclinic
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: ../../../app           # relative path from flux-system folder to Helm chart
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  values:
    replicaCount: 2
    service:
      type: ClusterIP
    image:
      repository: spring-petclinic/spring-petclinic
      tag: latest
